---
- name: Create a node
  hosts: 10.128.1.152
  connection: local
  vars:
    user: admin
    password: admin

  tasks:
          - name: delete a node - 'name' is the name of the node
            bigip_node:
                    server: "{{ inventory_hostname }}"
                    user: "{{ user }}"
                    password: admin
                    validate_certs: no
                    state: absent
                    name: "server2"
            delegate_to: localhost

