---
- name: Create a node
  hosts: 10.128.1.152
  connection: local

  tasks:
          - name: Create a node - 'name' is the ip of the node, 'address' is its address
            bigip_node:
                    server: "{{ inventory_hostname }}"
                    user: "{{ userName }}"
                    password: "{{ password }}"
                    validate_certs: no
                    address: "10.1.20.111"
                    name: "server2"
            delegate_to: localhost

