---
- name: Create a node
  hosts: 10.128.1.152
  connection: local

  tasks:
          - name: delete a node - 'name' is the name of the node, must be supplied either in a inventory file or command line
            bigip_node:
                    server: "{{ inventory_hostname }}"
                    user: "{{ user }}"
                    password: "{{ password }}"
                    validate_certs: no
                    state: absent
                    name: "{{ nodeip }}"
            delegate_to: localhost

